<?php

/**
 * @file
 * Redis module.
 *
 * This file is a placeholder for other modules that need the Redis client for
 * something else than lock and cache.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\redis\Hook\RedisHooks;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function redis_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(RedisHooks::class)->help($route_name, $route_match);
}
