<?php

/**
 * Implements hook_library_info_alter().
 *
 * Replaces style sheets declared in libraries with color-altered style sheets.
 */
function xinshi_editor_library_info_alter(&$libraries, $extension) {
  if ($extension == 'ace_editor') {
    $libraries['formatter']['js']['/libraries/ace-builds/src/ace.js']['preprocess'] = FALSE;
  }
}

/**
 * Implements hook_theme().
 */
function xinshi_editor_theme($existing, $type, $theme, $path) {
  return [
    'json_formatter' => [
      'template' => 'field--json-formatter',
      'variables' => ['value' => NULL,],
    ],
  ];
}


/**
 * Implements hook_block_alter().
 */
function xinshi_editor_block_alter(&$definitions) {
  foreach ($definitions as $key => $definition) {
    if (substr($key, 0, 14) == 'block_content:') {
      $definitions[$key]['class'] = 'Drupal\xinshi_editor\Plugin\Block\BlockContentBlock';
    }
  }
}
