views.display.rest_export_inner_nested:
  type: views_display_path
  label: 'REST export nested display options'
  mapping:
    auth:
      type: sequence
      label: 'Authentication'
      sequence:
        type: string
        label: 'Authentication Provider'
