views.display.rest_export_inner_nested:
  type: views.display.rest_export
  label: 'REST export nested display options'

views.display.rest_export_first_row:
  type: views.display.rest_export
  label: 'REST export first row display options'

views.style.xinshi_pager_serializer:
  type: views.style.serializer
  label: 'Serialized rows and pager options'
