<?php
/**
 * 云客支付模块
 * 开发方：未来很美（深圳）科技有限公司 官网：www.will-nice.com
 * 开发者：云客 phpworld@qq.com 个人站：www.indrupal.com
 */

/**
 * 执行计划任务
 */
function yunke_pay_cron() {
  //更新微信支付平台证书 每隔12小时自动更新一次
  $wechatConfig = \Drupal::config('yunke_pay.WeChat');
  $updateTime = $wechatConfig->get('wechatpayCertificateTime');
  if ((time() - (int) $updateTime) > 43200) {//更新时间大于12小时则自动更新
    \Drupal::service('yunke_pay.pay.wechat')->updateWechatCertificate();
  }
}
