<?php

/**
 * @file
 * Ckeditor_templates_ui module file.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Asset\AttachedAssetsInterface;

/**
 * Implements hook_help().
 *
 * {@inheritdoc}
 */
function ckeditor_templates_ui_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.ckeditor_templates_ui':
      $text = file_get_contents(dirname(__FILE__) . "/README.txt");
      if (!\Drupal::moduleHandler()->moduleExists('markdown')) {
        return '<pre>' . $text . '</pre>';
      }
      else {
        // Use the Markdown filter to render the README.
        $filter_manager = \Drupal::service('plugin.manager.filter');
        $settings = \Drupal::configFactory()->get('markdown.settings')->getRawData();
        $config = ['settings' => $settings];
        $filter = $filter_manager->createInstance('markdown', $config);
        return $filter->process($text, 'en');
      }
  }
  return NULL;

}

/**
 * Implements hook_ckeditor_plugin_info_alter().
 */
function ckeditor_templates_ui_ckeditor5_plugin_info_alter(array &$plugins) : void {
  // Change template plugin class.
  $plugins['ckeditor5_template_template']->setClass('Drupal\ckeditor_templates_ui\CkeditorTemplatesUi');
}

/**
* Implements hook_library_info_alter().
*/
function ckeditor_templates_ui_library_info_alter(&$libraries, $extension) {
  if ($extension == 'ckeditor5_template' && isset($libraries['template'])) {
    $new_path = '/' . \Drupal::service('extension.list.module')->getPath('ckeditor_templates_ui') . '/js/ckeditor_templates.js';
    $libraries['template']['js'] = [$new_path => ['minified' => 'true']];
  }
}