<?php

namespace Drupal\xinshi_legacy\Plugin\Field\FieldWidget;

use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\OpenModalDialogCommand;
use Drupal\Core\Entity\Entity\EntityFormDisplay;
use Drupal\Core\Field\FieldItemListInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\media\Entity\Media;
use Drupal\media_library\MediaLibraryUiBuilder;
use Drupal\views\Views;
use Drupal\media_library\Plugin\Field\FieldWidget\MediaLibraryWidget as CoreMediaLibraryWidget;
use Drupal\Component\Utility\Html;
use Drupal\Core\Url;

/**
 * Plugin implementation of the 'media_library_widget' widget.
 *
 * @FieldWidget(
 *   id = "xinshi_media_library_widget",
 *   label = @Translation("XINSHI Media library"),
 *   description = @Translation("Allows you to select items from the media library."),
 *   field_types = {
 *     "entity_reference"
 *   },
 *   multiple_values = TRUE,
 * )
 *
 * @internal
 *   Media Library is an experimental module and its internal code may be
 *   subject to change in minor releases. External code should not instantiate
 *   or extend this class.
 */
class MediaLibraryWidget extends CoreMediaLibraryWidget {


  /**
   * {@inheritdoc}
   */
  public static function defaultSettings() {
    return [
        'title' => 'Add or select media',
        'width' => '75%',
        'height' => '75%',
        'description' => 0,
        'border' => 0,
        'hidden_title' => 0,
        'view' => 'media_library',
        'display_id' => 'widget',
        'widget_grid' => '4',
        'edit' => '1',
      ] + parent::defaultSettings();
  }

  /**
   * {@inheritdoc}
   */
  public function settingsForm(array $form, FormStateInterface $form_state) {
    $form = parent::settingsForm($form, $form_state);
    $form['title'] = [
      '#type' => 'textfield',
      '#title' => t('Media dialog title'),
      '#default_value' => $this->getSetting('title'),
    ];

    $form['width'] = [
      '#type' => 'textfield',
      '#title' => t('Media dialog width'),
      '#default_value' => $this->getSetting('width'),
    ];

    $form['height'] = [
      '#type' => 'textfield',
      '#title' => t('Media dialog height'),
      '#default_value' => $this->getSetting('height'),
    ];

    $form['description'] = [
      '#type' => 'checkbox',
      '#title' => t('Display description'),
      '#default_value' => $this->getSetting('description'),
    ];

    $form['border'] = [
      '#type' => 'checkbox',
      '#title' => t('Display media selection wrapper border'),
      '#default_value' => $this->getSetting('border'),
    ];

    $form['hidden_title'] = [
      '#type' => 'checkbox',
      '#title' => t('Hidden field widget title'),
      '#default_value' => $this->getSetting('hidden_title'),
    ];

    $form['edit'] = [
      '#type' => 'checkbox',
      '#title' => t('Display Edit button'),
      '#default_value' => $this->getSetting('edit'),
    ];

    $form['widget_grid'] = [
      '#title' => $this->t('Display media items per row of widget'),
      '#type' => 'select',
      '#options' => ['1' => 1, '2' => 2, '3' => 3, '4' => 4, '5' => 5, '6' => 6, '10' => 10, '12' => 12],
      '#default_value' => $this->getSetting('widget_grid') ?: 4,
    ];

    $view_list = [];
    foreach (Views::getAllViews() as $key => $view) {
      if ($view->status() && $view->get('base_table') == 'media_field_data') {
        $view_list[$key] = $view->label();
      }
    }
    $form['display_id'] = [
      '#title' => $this->t('View'),
      '#type' => 'select',
      '#options' => $this->getViewDisplays($this->getSetting('view')),
      '#default_value' => $this->getSetting('display_id'),
      '#empty_option' => $this->t('- Select -'),
      '#empty_value' => '',
    ];

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function settingsSummary() {
    $summary = parent::settingsSummary(); // TODO: Change the autogenerated stub
    if ($value = $this->getSetting('title')) {
      $summary[] = $this->t('Media dialog title : @title', ['@title' => $value]);
    }
    if ($value = $this->getSetting('width')) {
      $summary[] = $this->t('Media dialog width : @width', ['@width' => $value]);
    }
    if ($value = $this->getSetting('height')) {
      $summary[] = $this->t('Media dialog height : @height', ['@height' => $value]);
    }

    $summary[] = $this->t('Display description : @value', ['@value' => t($this->getSetting('description') ? "Yes" : "No")]);
    $summary[] = $this->t('Display media selection wrapper border : @value', ['@value' => t($this->getSetting('border') ? "Yes" : "No")]);
    $summary[] = $this->t('Hidden field widget title : @value', ['@value' => t($this->getSetting('hidden_title') ? "Yes" : "No")]);
    $summary[] = $this->t('Display Edit button : @value', ['@value' => t($this->getSetting('edit') ? "Yes" : "No")]);
    $summary[] = $this->t('Display media items per row of widget : @value', ['@value' => $this->getSetting('widget_grid')]);

    return $summary;
  }

  /**
   * {@inheritdoc}
   */
  public function formElement(FieldItemListInterface $items, $delta, array $element, array &$form, FormStateInterface $form_state) {
    $element = parent::formElement($items, $delta, $element, $form, $form_state); // TODO: Change the autogenerated stub
    $element['#attached']['library'][] = 'xinshi_legacy/media_library_widget';

    $element['media_library_open_button']['#value'] = t('Add @title', ['@title' => $element['#title']]);
    $element['media_library_open_button']['#weight'] = -99;
    $element['media_library_update_widget']['#weight'] = -98;
    $element['media_library_update_widget']['#attributes']['class'][] = 'hidden';

    $element['empty_selection']['#weight'] = 0;
    $element['selection']['#weight'] = 99;
    $element['selection']['#attributes']['class'][] = 'xinshi-media-library-selection';
    $element['selection']['#attributes']['class'][] = 'media-library-selection-widget';
    $element['selection']['#attributes']['class'][] = 'media-library-selection-col-' . $this->getSetting('widget_grid');
    if ($this->getSetting('border') && isset($element['selection'][0])) {
      $element['selection']['#attributes']['class'][] = 'media-library-selection-border';
    }
    $element['#field_prefix']['weight_toggle']['#access'] = FALSE;
    $element['#attributes']['class'][] = 'fieldgroup';
    $element['#attributes']['class'][] = 'xinshi-media-library';
    if ($this->getSetting('hidden_title')) {
      $element['#attributes']['class'][] = 'xinshi-media-library-hidden-title';
      $element['open_button']['#value'] = t('Add @label', ['@label' => $element['#title']]);
    }
    if (empty($this->getSetting('description'))) {
      $element['#description'] = '';
      $element['#field_prefix']['empty_selection']['#access'] = FALSE;
    }

    if ($this->getSetting('edit')) {
      $parents = $form['#parents'];
      // Create an ID suffix from the parents to make sure each widget is unique.
      $id_suffix = $parents ? '-' . implode('-', $parents) : '';
      $field_name = $this->fieldDefinition->getName();
      $referenced_entities = $items->referencedEntities();
      foreach ($element['selection'] as $key => &$item) {
        if (!is_numeric($key)) {
          continue;
        }
        $entity = $referenced_entities[$key];
        if (!($entity instanceof Media && $entity->access('edit'))) {
          continue;
        }
        $media_id = $item['target_id']['#value'];
        $edit_url_query_params = [
          'media_library_edit' => 'ajax',
          'media_library_edit_field_name' => $field_name,
          'media_library_edit_entity_id' => $media_id,
          'media_library_edit_selector' => 'edit' . $id_suffix . '-' . Html::cleanCssIdentifier($field_name) . '-selection-' . $key,
        ];
        $item['#attributes']['id'] = 'edit' . $id_suffix . '-' . Html::cleanCssIdentifier($field_name) . '-selection-' . $key;
        $url = Url::fromRoute('entity.media.edit_form', ['media' => $media_id], ['query' => $edit_url_query_params])->toString();
        $dialog_options = MediaLibraryUiBuilder::dialogOptions();
        $item['edit_button'] = [
          '#type' => 'button',
          '#value' => $this->t('Edit'),
          '#attributes' => [
            'type' => 'button',
            'class' => ['edit-media',
              'use-ajax',
              'js-media-library-item-edit',
              'media-library-item__edit',
            ],
            'href' => $url,
            'data-dialog-type' => 'modal',
            'data-dialog-options' => json_encode([
              'height' => $dialog_options['height'],
              'width' => $dialog_options['width'],
              'classes' => ['ui-dialog-content' => 'media-library-edit__modal'],
            ]),
          ],
        ];
      }
    }

    return $element;
  }

  /**
   * {@inheritdoc}
   */
  public static function openMediaLibrary(array $form, FormStateInterface $form_state) {
    $triggering_element = $form_state->getTriggeringElement();
    $library_ui = \Drupal::service('media_library.ui_builder')->buildUi($triggering_element['#media_library_state']);
    $dialog_options = MediaLibraryUiBuilder::dialogOptions();
    $parameters = $triggering_element['#media_library_state']->get('media_library_opener_parameters');
    $field = current($triggering_element['#parents']);
    $form_display_mode = 'default';
    if ($form_display = $form_state->getStorage()['form_display']) {
      $form_display_mode = $form_display->getMode();
    }

    $display = \Drupal::entityTypeManager()
      ->getStorage('entity_form_display')
      ->load($parameters['entity_type_id'] . '.' . $parameters['bundle'] . '.' . $form_display_mode);
    if (empty($display)) {
      $form_display_mode = 'default';
      $display = \Drupal::entityTypeManager()
        ->getStorage('entity_form_display')
        ->load($parameters['entity_type_id'] . '.' . $parameters['bundle'] . '.' . $form_display_mode);
    }
    $settings = $display->get('content')[$parameters['field_name']]['settings'];
    $dialog_options['title'] = $settings['title'] ? t($settings['title']) : $dialog_options['title'];
    $dialog_options['width'] = $settings['width'];
    $dialog_options['height'] = $settings['height'];
    $display_id = $settings['display_id'];

    if ($display_id) {
      $library_ui['content']['view']['#display_id'] = $display_id;
      $view = Views::getView($settings['view']);
      $view->setDisplay($display_id);
      $view->setArguments($library_ui['content']['view']['#view']->args);
      $view->execute($display_id);
      $library_ui['content']['view']['#view'] = $view;
    } elseif (empty($display_id)) {
      unset($library_ui['content']['view']);
    }

    return (new AjaxResponse())
      ->addCommand(new OpenModalDialogCommand($dialog_options['title'], $library_ui, $dialog_options));
  }

  /**
   * Get displays for a particular view.
   *
   * @param string $view_id
   *   The view ID.
   *
   * @return array
   *   An array containing displays for the view.
   */
  protected function getViewDisplays($view_id) {
    $options = [];
    $view_plugins = ['page', 'block'];
    /** @var \Drupal\views\Entity\View $view */
    if ($view = \Drupal::service('entity_type.manager')->getStorage('view')->load($view_id)) {
      if ($displays = $view->get('display')) {
        foreach ($displays as $display) {
          if (in_array($display['display_plugin'], $view_plugins, TRUE)) {
            $options[$display['id']] = $display['display_title'];
          }
        }
      }
    }
    return $options;
  }
}
