<?php

namespace Drupal\xinshi_api\Form;

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Form\ConfigFormBase;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\NodeType;
use Drupal\taxonomy\Entity\Vocabulary;

class SettingsForm extends ConfigFormBase {

  private $configName = 'xinshi_api.settings';

  /**
   * {@inheritdoc}
   */
  public function getFormId() {
    return 'xinshi_api_settings_form';
  }

  /**
   * {@inheritdoc}
   */
  protected function getEditableConfigNames() {
    return [$this->configName];
  }

  /**
   * {@inheritdoc}
   */
  public function buildForm(array $form, FormStateInterface $form_state) {
 $modules=[
      'action',
      'announcements_feed',
      'automated_cron',
      'ban',
      'basic_auth',
      'big_pipe',
      'block',
      'block_content',
      'book',
      'breakpoint',
      'ckeditor5',
      'comment',
      'config',
      'config_translation',
      'contact',
      'content_moderation',
      'content_translation',
      'contextual',
      'datetime',
      'datetime_range',
      'dblog',
      'dynamic_page_cache',
      'editor',
      'field',
      'field_layout',
      'field_ui',
      'file',
      'filter',
      'forum',
      'help',
      'help_topics',
      'history',
      'image',
      'inline_form_errors',
      'jsonapi',
      'language',
      'layout_builder',
      'layout_builder_expose_all_field_blocks',
      'layout_discovery',
      'link',
      'locale',
      'media',
      'media_library',
      'menu_link_content',
      'menu_ui',
      'migrate',
      'migrate_drupal',
      'migrate_drupal_ui',
      'mysql',
      'navigation_top_bar',
      'navigation',
      'node',
      'options',
      'page_cache',
      'path',
      'path_alias',
      'pgsql',
      'phpass',
      'responsive_image',
      'rest',
      'sdc',
      'search',
      'serialization',
      'settings_tray',
      'shortcut',
      'sqlite',
      'statistics',
      'syslog',
      'system',
      'taxonomy',
      'telephone',
      'text',
      'toolbar',
      'tour',
      'tracker',
      'update',
      'user',
      'views',
      'views_ui',
      'workflows',
      'workspaces',
      'ace_editor',
      'acquia_connector',
      'address',
      'admin_toolbar',
      'admin_toolbar_links_access_filter',
      'admin_toolbar_search',
      'admin_toolbar_tools',
      'advancedqueue',
      'allowed_formats',
      'autocomplete_deluxe',
      'autologout',
      'autosave_form',
      'better_exposed_filters',
      'blazy',
      'blazy_layout',
      'blazy_ui',
      'bootstrap_layout_builder',
      'bootstrap_styles',
      'charts',
      'charts_api_example',
      'charts_billboard',
      'charts_blocks',
      'charts_c3',
      'charts_chartjs',
      'charts_google',
      'charts_highcharts',
      'chosen',
      'chosen_field',
      'chosen_lib',
      'ckeditor',
      'ckeditor5_template',
      'ckeditor_font',
      'ckeditor_templates',
      'ckeditor_templates_ui',
      'ckeditor_textindent',
      'codesnippet',
      'color',
      'colorbox',
      'colorbutton',
      'comment_delete',
      'commerce',
      'commerce_cart',
      'commerce_checkout',
      'commerce_log',
      'commerce_number_pattern',
      'commerce_order',
      'commerce_payment',
      'commerce_payment_example',
      'commerce_price',
      'commerce_product',
      'commerce_promotion',
      'commerce_store',
      'commerce_tax',
      'config_filter',
      'config_ignore',
      'conflict',
      'conflict_paragraphs',
      'content_lock',
      'content_lock_timeout',
      'core_context',
      'crop',
      'crop_media_entity',
      'csv_serialization',
      'ctools',
      'ctools_block',
      'ctools_entity_mask',
      'ctools_views',
      'devel',
      'devel_generate',
      'diff',
      'dropzonejs',
      'dropzonejs_eb_widget',
      'dynamic_entity_reference',
      'easy_breadcrumb',
      'eck',
      'elasticsearch_connector',
      'embed',
      'entity',
      'entity_browser',
      'entity_browser_example',
      'entity_browser_entity_form',
      'entity_embed',
      'entity_print',
      'entity_print_views',
      'entity_reference_revisions',
      'entity_share',
      'entity_share_async',
      'entity_share_client',
      'entity_share_diff',
      'entity_share_lock',
      'entity_share_server',
      'entity_theme_engine',
      'field_group_migrate',
      'field_group',
      'field_group_accordion',
      'field_permissions',
      'field_validation',
      'field_validation_legacy',
      'file_mdm',
      'file_mdm_exif',
      'file_mdm_font',
      'fivestar',
      'flag',
      'flag_bookmark',
      'flag_count',
      'flag_follower',
      'footable',
      'forms_steps',
      'fpa',
      'gin_toolbar',
      'image_effect',
      'image_effects',
      'image_widget_crop',
      'image_widget_crop_examples',
      'inline_entity_form',
      'jquery_ui',
      'jquery_ui_autocomplete',
      'jquery_ui_draggable',
      'jquery_ui_droppable',
      'jquery_ui_menu',
      'js_cookie',
      'jsonapi_extras',
      'jsonapi_defaults',
      'jsonapi_include',
      'key_value',
      'layout_library',
      'login_emailusername',
      'mailsystem',
      'media_entity_instagram',
      'media_entity_twitter',
      'media_library_form_element',
      'menu_breadcrumb',
      'menu_item_extras',
      'mie_demo_base',
      'menu_per_role',
      'message',
      'message_example',
      'message_notify',
      'message_notify_example',
      'message_subscribe',
      'message_subscribe_email',
      'message_subscribe_example',
      'message_subscribe_ui',
      'message_ui',
      'message_notify_ui',
      'message_ui_test',
      'metatag',
      'metatag_app_links',
      'metatag_custom_tags',
      'metatag_dc',
      'metatag_dc_advanced',
      'metatag_extended_perms',
      'metatag_facebook',
      'metatag_favicons',
      'metatag_google_cse',
      'metatag_google_plus',
      'metatag_hreflang',
      'metatag_mobile',
      'metatag_open_graph',
      'metatag_open_graph_products',
      'metatag_page_manager',
      'metatag_pinterest',
      'metatag_routes',
      'metatag_twitter_cards',
      'metatag_verification',
      'metatag_views',
      'migrate_source_csv',
      'migrate_tools',
      'module_filter',
      'multiselect',
      'node_edit_protection',
      'page_load_progress',
      'page_manager',
      'page_manager_ui',
      'panelbutton',
      'panelizer',
      'panelizer_quickedit',
      'panels',
      'panels_ipe',
      'paragraphs_demo',
      'paragraphs_library',
      'paragraphs_type_permissions',
      'paragraphs',
      'paragraphs_tabs_widget',
      'pathauto',
      'private_message_notify',
      'private_message',
      'profile',
      'profile_switcher',
      'queue_ui',
      'quick_node_clone',
      'quickedit',
      'range',
      'rdf',
      'recently_read',
      'redirect_404',
      'redirect_domain',
      'redirect',
      'redis',
      'require_login',
      'rest_views_geo',
      'rest_views_revisions',
      'rest_views_search_api',
      'rest_views',
      'restui',
      'search_api_db',
      'search_api_db_defaults',
      'search_api',
      'select_or_other',
      'serial',
      'shs_chosen',
      'shs',
      'slick_ui',
      'slick',
      'slick_entityreference',
      'sms_blast',
      'sms_devel',
      'sms_sendtophone',
      'sms_user',
      'sms',
      'state_machine',
      'switch_page_theme',
      'token',
      'toolbar_visibility',
      'unique_content_field_validation',
      'user_default_page',
      'verf',
      'vem_migrate_oembed',
      'video_embed_media',
      'video_embed_wysiwyg',
      'video_embed_field',
      'views_add_button',
      'actions_permissions',
      'views_bulk_operations_example',
      'views_bulk_operations',
      'views_custom_cache_tag_demo',
      'views_custom_cache_tag',
      'views_data_export',
      'views_infinite_scroll',
      'views_table_rowspan',
      'viewsreference',
      'votingapi_tokens',
      'votingapi',
      'webform_access',
      'webform_attachment',
      'webform_bootstrap',
      'webform_cards',
      'webform_clientside_validation',
      'webform_demo_application_evaluation',
      'webform_demo_event_registration',
      'webform_demo_region_contact',
      'webform_devel',
      'webform_entity_print',
      'webform_entity_print_attachment',
      'webform_example_composite',
      'webform_example_custom_form',
      'webform_example_element',
      'webform_example_element_properties',
      'webform_example_handler',
      'webform_example_remote_post',
      'webform_example_variant',
      'webform_examples',
      'webform_examples_accessibility',
      'webform_icheck',
      'webform_image_select',
      'webform_jqueryui_buttons',
      'webform_jqueryui_datepicker',
      'webform_location_geocomplete',
      'webform_location_places',
      'webform_node',
      'webform_options_custom',
      'webform_options_limit',
      'webform_scheduled_email',
      'webform_schema',
      'webform_share',
      'webform_shortcuts',
      'webform_submission_export_import',
      'webform_submission_log',
      'webform_templates',
      'webform_toggles',
      'webform_ui',
      'webform',
      'webform_rest',
      'webform_views_example',
      'webform_views',
      'xls_serialization',
      'xmlsitemap',
      'xmlsitemap_custom',
      'xmlsitemap_engines',
      'standard',
 ];

    $installed = [
      'ace_editor',
      'address',
      'admin_toolbar',
      'admin_toolbar_tools',
      'allowed_formats',
      'autogrow',
      'automated_cron',
      'big_pipe',
      'block',
      'block_content',
      'breakpoint',
      'chosen',
      'chosen_lib',
      'ckeditor',
      'ckeditor_font',
      'ckeditor_textindent',
      'codesnippet',
      'color',
      'colorbox',
      'comment',
      'config',
      'config_filter',
      'config_ignore',
      'config_translation',
      'conflict',
      'contact',
      'content_moderation',
      'contextual',
      'core_context',
      'crop',
      'ctools',
      'ctools_block',
      'datetime',
      'datetime_range',
      'dblog',
      'devel',
      'devel_generate',
      'devel_php',
      'diff',
      'dynamic_entity_reference',
      'dynamic_page_cache',
      'eck',
      'editor',
      'embed',
      'entity_browser',
      'entity_embed',
      'entity_reference_revisions',
      'entity_share',
      'entity_share_client',
      'entity_theme_engine',
      'field',
      'field_group',
      'field_permissions',
      'field_ui',
      'file',
      'filter',
      'flag',
      'footable',
      'help',
      'history',
      'image',
      'image_widget_crop',
      'inline_entity_form',
      'jquery_ui',
      'jquery_ui_draggable',
      'jquery_ui_droppable',
      'json_editor',
      'jsonapi',
      'jsonapi_extras',
      'jsonapi_include',
      'key_value',
      'language',
      'layout_builder',
      'layout_discovery',
      'layout_library',
      'link',
      'locale',
      'mailsystem',
      'media',
      'media_library',
      'menu_item_extras',
      'menu_link_content',
      'menu_ui',
      'message',
      'message_notify',
      'message_subscribe',
      'message_ui',
      'metatag',
      'migrate',
      'migrate_drupal',
      'mysql',
      'node',
      'options',
      'otp_login',
      'panelizer',
      'panels',
      'panels_ipe',
      'path',
      'path_alias',
      'quickedit',
      'range',
      'rdf',
      'redirect',
      'redis',
      'rest',
      'restui',
      'search',
      'search_api',
      'search_api_db',
      'serialization',
      'shortcut',
      'sms',
      'sms_user',
      'swiftmailer',
      'switch_page_theme',
      'system',
      'taxonomy',
      'telephone',
      'text',
      'token',
      'toolbar',
      'toolbar_visibility',
      'tour',
      'user',
      'video_embed_field',
      'views_add_button',
      'views_bulk_operations',
      'views_ui',
      'viewsreference',
      'webform',
      'webform_rest',
      'webform_ui',
      'webform_views',
      'workflows',
      'xinshi_api',
      'xinshi_editor',
      'xinshi_sms',
      'xinshi_views',
      'xmlsitemap_engines',
      'pathauto',
      'xmlsitemap',
      'content_translation',
      'views',
      'paragraphs',
      'standard'
    ];

    $nlist = [];
    foreach($installed as $val) {
      if(!in_array($val,$modules)) {
        $nlist[]=$val;
      }
    }

    dump(implode(",\n", $nlist) . ",");
    exit;
    $config = $this->configFactory->get($this->configName);
    $form['page'] = [
      '#type' => 'details',
      '#title' => t('Page Settings'),
    ];

    $form['page']['not_found'] = [
      '#type' => 'text_format',
      '#title' => t('Page Not Found Json'),
      '#format' => 'json',
      '#allowed_formats' => ['json'],
      '#default_value' => $config->get('page')['not_found'] ?? '',
    ];

    $form['page']['access_denied'] = [
      '#type' => 'text_format',
      '#title' => t('Access Denied Json'),
      '#format' => 'json',
      '#allowed_formats' => ['json'],
      '#default_value' => $config->get('page')['access_denied'] ?? '',
    ];

    $form['cache_enable'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Enable entity context cache'),
      '#default_value' => $config->get('cache_enable'),
    ];

    $form['entity'] = [
      '#type' => 'details',
      '#title' => t('Entity Cache Context'),
      '#open' => TRUE,
    ];


    $form['entity']['node_cache'] = [
      '#type' => 'table',
      '#caption' => $this->t('Node context cache'),
      '#header' => [$this->t('Content type'), $this->t('Cache')],
      '#states' => [
        'visible' => [
          ':input[name="cache_enable"]' => ['checked' => TRUE],
        ],
      ],
    ];
    /** @var NodeType[] $node_types */
    $types = NodeType::loadMultiple();
    foreach ($types as $key => $type) {
      $cache_context = $config->get('node_cache');
      $form['entity']['node_cache'][$key]['name'] = [
        '#type' => 'label',
        '#title' => $type->label(),
      ];
      $form['entity']['node_cache'][$key]['context'] = [
        '#type' => 'checkboxes',
        '#title_display' => 'invisible',
        '#options' => [
          'user' => $this->t('User'),
        ],
        '#default_value' => isset($cache_context[$key]['context']) ? $cache_context[$key]['context'] : [],
      ];
    }

    $form['entity']['taxonomy_term_cache'] = [
      '#type' => 'table',
      '#caption' => $this->t('Vocabulary context cache'),
      '#header' => [$this->t('vocabulary'), $this->t('Cache')],
    ];
    /** @var Vocabulary[] $node_types */
    $types = Vocabulary::loadMultiple();
    foreach ($types as $key => $type) {
      $cache_context = $config->get('taxonomy_term_cache');
      $form['entity']['taxonomy_term_cache'][$key]['name'] = [
        '#type' => 'label',
        '#title' => $type->label(),
      ];
      $form['entity']['taxonomy_term_cache'][$key]['context'] = [
        '#type' => 'checkboxes',
        '#title_display' => 'invisible',
        '#options' => [
          'user' => $this->t('User'),
        ],
        '#default_value' => isset($cache_context[$key]['context']) ? $cache_context[$key]['context'] : [],
      ];
    }

    $form['entity']['user_cache'] = [
      '#type' => 'table',
      '#caption' => $this->t('User cache'),
      '#header' => [$this->t('vocabulary'), $this->t('Cache')],
    ];

    $key = 'user';
    $cache_context = $config->get('user_cache');
    $form['entity']['user_cache'][$key]['name'] = [
      '#type' => 'label',
      '#title' => $this->t("User"),
    ];
    $form['entity']['user_cache'][$key]['context'] = [
      '#type' => 'checkboxes',
      '#title_display' => 'invisible',
      '#options' => [
        'user' => $this->t('User'),
      ],
      '#default_value' => isset($cache_context[$key]['context']) ? $cache_context[$key]['context'] : [],
    ];


    $form['debug'] = [
      '#type' => 'checkbox',
      '#title' => $this->t('Debug'),
      '#default_value' => $config->get('debug'),
    ];
    return parent::buildForm($form, $form_state);
  }

  /**
   * {@inheritdoc}
   */
  public function validateForm(array &$form, FormStateInterface $form_state) {
    $url = $form_state->getValue('front_domain');
    if ($url && !UrlHelper::isExternal($url)) {
      $form_state->setErrorByName('front_domain', t('Invalid url'));
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitForm(array &$form, FormStateInterface $form_state) {
    $config = $this->configFactory->getEditable($this->configName);
    $config->set('page', [
      'not_found' => $form_state->getValue(['not_found', 'value']),
      'access_denied' => $form_state->getValue(['access_denied', 'value'])
    ])
      ->set('node_cache', $form_state->getValue('node_cache'))
      ->set('taxonomy_term_cache', $form_state->getValue('taxonomy_term_cache'))
      ->set('cache_enable', $form_state->getValue('cache_enable'))
      ->set('user_cache', $form_state->getValue('user_cache'))
      ->set('debug', $form_state->getValue('debug'))
      ->save();
    parent::submitForm($form, $form_state);
  }
}
